-- Master SQL Setup for MCE Command Center
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. Create Projects Table
CREATE TABLE IF NOT EXISTS projects_master (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    PROJECT_UID uuid,
    PROJECT_CODE text,
    PROJECT_NAME text,
    PROJECT_TYPE text,
    CLIENT_ENTITY_UID uuid,
    CLIENT_NAME text,
    END_CLIENT_NAME text,
    DEVELOPER_NAME text,
    MAIN_CONTRACTOR_NAME text,
    CONTRACT_UID uuid,
    CONTRACT_TITLE text,
    CONTRACT_FORM text,
    CONTRACT_SIGNED_DATE timestamptz,
    NOTICE_TO_PROCEED_DATE timestamptz,
    PROJECT_COMMENCEMENT_DATE timestamptz,
    PROJECT_COMPLETION_DATE_PLANNED timestamptz,
    PROJECT_COMPLETION_DATE_ACTUAL timestamptz,
    DEFECTS_LIABILITY_PERIOD_MONTHS integer,
    DEFECTS_LIABILITY_END_DATE timestamptz,
    SCOPE_OF_SERVICES_ENUM text,
    SERVICES_SCOPE_JSON jsonb,
    DELIVERABLE_REGISTER_JSON jsonb,
    DELIVERABLE_SCHEDULE_APPROVED_DATE timestamptz,
    MILESTONE_BASELINE_JSON jsonb,
    MILESTONE_CURRENT_JSON jsonb,
    CHANGE_CONTROL_REQUIRED boolean,
    VARIATION_ORDERS_COUNT integer,
    VARIATION_APPROVED_VALUE numeric(18,2),
    VARIATION_PENDING_VALUE numeric(18,2),
    CLAIMS_SUBMITTED_COUNT integer,
    CLAIMS_VALUE_SUBMITTED numeric(18,2),
    CLAIMS_VALUE_DETERMINED numeric(18,2),
    LD_APPLICABLE boolean,
    LD_BASIS text,
    LD_RATE_VALUE numeric(18,2),
    LD_CAP_PERCENT_CONTRACT_VALUE numeric(5,2),
    RETENTION_PERCENT numeric(5,2),
    ADVANCE_PAYMENT_PERCENT numeric(5,2),
    PERFORMANCE_BOND_REQUIRED boolean,
    PERFORMANCE_BOND_PERCENT numeric(5,2),
    PERFORMANCE_BOND_ISSUE_DATE timestamptz,
    PERFORMANCE_BOND_EXPIRY_DATE timestamptz,
    ADVANCE_PAYMENT_BOND_REQUIRED boolean,
    ADVANCE_PAYMENT_BOND_EXPIRY_DATE timestamptz,
    PI_INSURANCE_REQUIRED boolean,
    PI_SUM_INSURED numeric(18,2),
    PI_POLICY_NUMBER text,
    PI_POLICY_EXPIRY_DATE timestamptz,
    THIRD_PARTY_LIABILITY_REQUIRED boolean,
    THIRD_PARTY_LIABILITY_SUM numeric(18,2),
    INVOICE_METHOD text,
    PAYMENT_TERMS_DAYS integer,
    PAYMENT_CURRENCY text,
    CONTRACT_VALUE_EXCL_VAT numeric(18,2),
    VAT_RATE_PERCENT numeric(5,2),
    AUTHORITY_APPROVAL_MATRIX_JSON jsonb,
    AUTHORITY_FEES_PAYABLE_BY text,
    AUTHORITY_FEES_PROVISIONAL_SUM numeric(18,2),
    PROJECT_LOCATION_COUNTRY text,
    PROJECT_LOCATION_EMIRATE text,
    PROJECT_LOCATION_CITY text,
    PROJECT_STATUS text,
    COMMUNICATION_PROTOCOL text,
    DELIVERY_RISK_RATING text,
    CONFLICT_RESOLUTION_CLAUSE text,
    LIABILITY_CAP_PERCENT_OF_FEES numeric(5,2),
    INDEMNITY_SCOPE_ENUM text,
    IP_OWNERSHIP text,
    CONFIDENTIALITY_CLASS text,
    DATA_PROCESSING_ADDENDUM_SIGNED boolean,
    SUSTAINABILITY_REQUIREMENTS_ENUM text,
    HSE_PLAN_REQUIRED boolean,
    HSE_PLAN_APPROVED_DATE timestamptz,
    SITE_ACCESS_PERMITS_REQUIRED boolean,
    SITE_HSE_INDUCTION_REQUIRED boolean,
    DOC_CONTROL_PLATFORM text,
    RFI_TURNAROUND_DAYS integer,
    SUBMITTAL_TURNAROUND_DAYS integer,
    SNAGGING_SCOPE_REQUIRED boolean,
    HANDOVER_DOCUMENTS_LIST_JSON jsonb,
    ORG_UNIT text,
    PROJECT_MANAGER_UID uuid,
    KEY_STAFF_LIST_JSON jsonb,
    TEAM_FTE_ALLOCATED text,
    CRITICAL_COMPETENCIES_GAPS_JSON jsonb,
    RESOURCE_PLAN_LOCK_DATE timestamptz,
    TIMESHEET_APPROVAL_CADENCE text,
    WPS_COMPLIANCE_REQUIRED boolean,
    WPS_COMPLIANCE_STATUS text,
    PAYROLL_COST_RATECARD_JSON jsonb,
    COST_CODE text,
    COST_CENTER text,
    BUDGET_LABOUR_HOURS integer,
    BUDGET_LABOUR_VALUE numeric(18,2),
    BUDGET_OPEX_VALUE numeric(18,2),
    COMMITTED_COSTS_VALUE numeric(18,2),
    FORECAST_TO_COMPLETE_VALUE numeric(18,2),
    EARNED_VALUE numeric(18,2),
    CPI_INDEX text,
    SPI_INDEX text,
    AR_OPEN_BALANCE numeric(18,2),
    AP_OPEN_BALANCE numeric(18,2),
    AR_BUCKET_0_30 numeric(18,2),
    AR_BUCKET_31_60 numeric(18,2),
    AR_BUCKET_61_90 numeric(18,2),
    AR_BUCKET_90_PLUS numeric(18,2),
    AP_BUCKET_0_30 numeric(18,2),
    AP_BUCKET_31_60 numeric(18,2),
    AP_BUCKET_61_90 numeric(18,2),
    AP_BUCKET_90_PLUS numeric(18,2),
    EXPECTED_COLLECTION_DATE timestamptz,
    COLLECTION_RISK_SCORE text,
    CASH_FLOW_FORECAST_30D numeric(18,2),
    CASH_FLOW_FORECAST_60D numeric(18,2),
    CASH_FLOW_FORECAST_90D numeric(18,2),
    BANK_GUARANTEE_COLLATERAL_PCT numeric(5,2),
    INSURANCE_RENEWAL_ALERT_DATE timestamptz,
    AUDIT_TRAIL_REQUIRED boolean,
    SOX_EQUIVALENT_CONTROLS boolean,
    APPROVAL_DOA_LEVEL text,
    LEGAL_HOLDS_ACTIVE boolean,
    LEGAL_NOTICE_ACTIVE boolean,
    DISPUTE_STATUS text,
    RISK_REGISTER_JSON jsonb,
    TOP_RISKS_P90_VALUE numeric(18,2),
    MITIGATION_ACTIONS_JSON jsonb,
    QHSE_INCIDENTS_COUNT integer,
    QHSE_NONCONFORMITIES_OPEN integer,
    AUTHORITY_SUBMISSIONS_OPEN integer,
    AUTHORITY_APPROVALS_PENDING integer,
    DOC_CONTROL_OVERDUE_TRANSMITTALS integer,
    RFI_OVERDUE_COUNT integer,
    SUBMITTAL_OVERDUE_COUNT integer,
    CLIENT_SATISFACTION_SCORE text,
    NPS_SCORE integer,
    HANDOVER_READINESS_PERCENT numeric(5,2),
    FINAL_ACCOUNT_AGREED_DATE timestamptz,
    RETENTION_HELD_VALUE numeric(18,2),
    RETENTION_RELEASE_DLP1_DATE timestamptz,
    RETENTION_RELEASE_DLP2_DATE timestamptz,
    RETENTION_RELEASE_AMOUNT_TOTAL numeric(18,2),
    PROJECT_CLOSEOUT_PACK_COMPLETED boolean,
    RECORDS_RETENTION_YEARS integer,
    DATA_CLASSIFICATION text,
    CYBERSEC_REQUIREMENTS_ENUM text,
    ACCESS_CONTROL_MATRIX_JSON jsonb,
    INTEGRATION_KEYS_JSON jsonb,
    INTEGRATION_GL_ACCOUNT_MAP_JSON jsonb,
    KPI_DASHBOARD_URL text,
    PLAYBOOK_VERSION text,
    LAST_REVIEWED_AT timestamptz,
    OWNER_FUNCTION text,
    REMEDIATION_SLA_DAYS integer,
    ALERT_SEVERITY text,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- 2. Enable Realtime
alter publication supabase_realtime add table projects_master;

-- 3. Seed Data
INSERT INTO projects_master (PROJECT_NAME, CLIENT_NAME, PROJECT_CODE, PROJECT_LOCATION_CITY, PROJECT_STATUS, CONTRACT_VALUE_EXCL_VAT) VALUES ('New Corniche Hospital', 'RAFED', '2023.010.HLT.012', 'Abu Dhabi', 'Construction', 57000000.0);
INSERT INTO projects_master (PROJECT_NAME, CLIENT_NAME, PROJECT_CODE, PROJECT_LOCATION_CITY, PROJECT_STATUS, CONTRACT_VALUE_EXCL_VAT) VALUES ('New Corniche Hospital - Royal Suites - V01', 'RAFED', '', 'Abu Dhabi', 'Tender Documents', 1638308.0);
INSERT INTO projects_master (PROJECT_NAME, CLIENT_NAME, PROJECT_CODE, PROJECT_LOCATION_CITY, PROJECT_STATUS, CONTRACT_VALUE_EXCL_VAT) VALUES ('New Corniche Hospital - Royal Suites - V02', 'RAFED', '', 'Abu Dhabi', 'Tender Documents', 1227096.0);
INSERT INTO projects_master (PROJECT_NAME, CLIENT_NAME, PROJECT_CODE, PROJECT_LOCATION_CITY, PROJECT_STATUS, CONTRACT_VALUE_EXCL_VAT) VALUES ('New Corniche Hospital - SKMC Retail / Mosque - V03', 'RAFED', '', 'Abu Dhabi', 'Awaiting Building Permit', 140000.0);
INSERT INTO projects_master (PROJECT_NAME, CLIENT_NAME, PROJECT_CODE, PROJECT_LOCATION_CITY, PROJECT_STATUS, CONTRACT_VALUE_EXCL_VAT) VALUES ('New Corniche Hospital - Biomed Tender Package - V04', 'RAFED', '', 'Abu Dhabi', 'Client Review', 300000.0);
INSERT INTO projects_master (PROJECT_NAME, CLIENT_NAME, PROJECT_CODE, PROJECT_LOCATION_CITY, PROJECT_STATUS, CONTRACT_VALUE_EXCL_VAT) VALUES ('AD Police Saadiyat D2', 'AD POLICE', '', 'Abu Dhabi', 'Tender Stage', 1212522.6432000005);
INSERT INTO projects_master (PROJECT_NAME, CLIENT_NAME, PROJECT_CODE, PROJECT_LOCATION_CITY, PROJECT_STATUS, CONTRACT_VALUE_EXCL_VAT) VALUES ('AD Police Saadiyat D3', 'AD POLICE', '', 'Abu Dhabi', 'Construction Ongoing', 1215976.8768);
INSERT INTO projects_master (PROJECT_NAME, CLIENT_NAME, PROJECT_CODE, PROJECT_LOCATION_CITY, PROJECT_STATUS, CONTRACT_VALUE_EXCL_VAT) VALUES ('AD Police Training Hangar - Tarif', 'AD POLICE', '', 'Abu Dhabi', 'Construction Ongoing', 1248975.04);
INSERT INTO projects_master (PROJECT_NAME, CLIENT_NAME, PROJECT_CODE, PROJECT_LOCATION_CITY, PROJECT_STATUS, CONTRACT_VALUE_EXCL_VAT) VALUES ('Civil Defence Al Shawamekh - C', 'AD POLICE', '', 'Abu Dhabi', 'Tender Stage', 1928500.0);
INSERT INTO projects_master (PROJECT_NAME, CLIENT_NAME, PROJECT_CODE, PROJECT_LOCATION_CITY, PROJECT_STATUS, CONTRACT_VALUE_EXCL_VAT) VALUES ('AD Police Beda Mutawah', 'AD POLICE', '', 'Abu Dhabi', 'Tender Stage', 1465721.82116);
INSERT INTO projects_master (PROJECT_NAME, CLIENT_NAME, PROJECT_CODE, PROJECT_LOCATION_CITY, PROJECT_STATUS, CONTRACT_VALUE_EXCL_VAT) VALUES ('AD Police, Emergency, and Civil Defence - Rahayel', 'AD POLICE', '', 'Abu Dhabi', 'Tender Stage', 1047290.4);
INSERT INTO projects_master (PROJECT_NAME, CLIENT_NAME, PROJECT_CODE, PROJECT_LOCATION_CITY, PROJECT_STATUS, CONTRACT_VALUE_EXCL_VAT) VALUES ('STMC Multi-Storey Parking', 'RAFED', '2024.004.HLT-002', 'Al Ain', 'Schematic Stage (Design)', 985000.0);
INSERT INTO projects_master (PROJECT_NAME, CLIENT_NAME, PROJECT_CODE, PROJECT_LOCATION_CITY, PROJECT_STATUS, CONTRACT_VALUE_EXCL_VAT) VALUES ('Long Term Care Center', 'Al Jalila Foundation', '', 'Dubai', 'Concept Stage (Design)', 8016400.0);
INSERT INTO projects_master (PROJECT_NAME, CLIENT_NAME, PROJECT_CODE, PROJECT_LOCATION_CITY, PROJECT_STATUS, CONTRACT_VALUE_EXCL_VAT) VALUES ('Majlis (2) Al Dhafra', 'Presidential Court', '', 'Abu Dhabi, Western Region', 'Construction Ongoing', 1676000.0);
INSERT INTO projects_master (PROJECT_NAME, CLIENT_NAME, PROJECT_CODE, PROJECT_LOCATION_CITY, PROJECT_STATUS, CONTRACT_VALUE_EXCL_VAT) VALUES ('Majalis Phase 3 (No 5) Supervision', 'Presidential Court', '', 'Abu Dhabi, Western Region', 'Construction Ongoing', 3467000.0);
INSERT INTO projects_master (PROJECT_NAME, CLIENT_NAME, PROJECT_CODE, PROJECT_LOCATION_CITY, PROJECT_STATUS, CONTRACT_VALUE_EXCL_VAT) VALUES ('Abu Dhabi Stem Cell Research Lab & Hospital', 'Abu Dhabi Stem Cell Center', '', 'Abu Dhabi', 'Ongoing', 36249549.0);
INSERT INTO projects_master (PROJECT_NAME, CLIENT_NAME, PROJECT_CODE, PROJECT_LOCATION_CITY, PROJECT_STATUS, CONTRACT_VALUE_EXCL_VAT) VALUES ('Arab Monetary Fund Fitout & Façade', 'Arab Monetary Fund', '', 'Abu Dhabi', 'Construction Ongoing', 2358333.0);
INSERT INTO projects_master (PROJECT_NAME, CLIENT_NAME, PROJECT_CODE, PROJECT_LOCATION_CITY, PROJECT_STATUS, CONTRACT_VALUE_EXCL_VAT) VALUES ('Al Kheiran Villa ', 'Presidential Court', '', 'Abu Dhabi', 'Ongoing', 3266300.0);
INSERT INTO projects_master (PROJECT_NAME, CLIENT_NAME, PROJECT_CODE, PROJECT_LOCATION_CITY, PROJECT_STATUS, CONTRACT_VALUE_EXCL_VAT) VALUES ('Al Ghurair Rehabilitation Center', 'Al Ghurair Centre', '', 'Dubai, UAE', 'Completed', 1784900.0);
INSERT INTO projects_master (PROJECT_NAME, CLIENT_NAME, PROJECT_CODE, PROJECT_LOCATION_CITY, PROJECT_STATUS, CONTRACT_VALUE_EXCL_VAT) VALUES ('Perla Towers 1', 'Emirates Limited ', '', 'Abu Dhabi', 'Completed', 2608000.0);
INSERT INTO projects_master (PROJECT_NAME, CLIENT_NAME, PROJECT_CODE, PROJECT_LOCATION_CITY, PROJECT_STATUS, CONTRACT_VALUE_EXCL_VAT) VALUES ('SSMC Staff Parking Phase I', 'SSMC/RAFED', '', 'Abu Dhabi', 'Completed ', 3953012.0);
INSERT INTO projects_master (PROJECT_NAME, CLIENT_NAME, PROJECT_CODE, PROJECT_LOCATION_CITY, PROJECT_STATUS, CONTRACT_VALUE_EXCL_VAT) VALUES ('SSMC Staff Parking Phase II', 'SSMC/RAFED', '', 'Abu Dhabi', 'DLP Period', 7915590.0);
INSERT INTO projects_master (PROJECT_NAME, CLIENT_NAME, PROJECT_CODE, PROJECT_LOCATION_CITY, PROJECT_STATUS, CONTRACT_VALUE_EXCL_VAT) VALUES ('Tawazun Industrial Park', 'Tawazun', '', 'Abu Dhabi', 'nan', 13573000.0);
INSERT INTO projects_master (PROJECT_NAME, CLIENT_NAME, PROJECT_CODE, PROJECT_LOCATION_CITY, PROJECT_STATUS, CONTRACT_VALUE_EXCL_VAT) VALUES ('Facelift Enhancement Projects at SKMC and Tawam Hospital', 'RAFED', '', 'Abu Dhabi & Al Ain', 'Pre-Award / Tender Stage', 23425855.74);
INSERT INTO projects_master (PROJECT_NAME, CLIENT_NAME, PROJECT_CODE, PROJECT_LOCATION_CITY, PROJECT_STATUS, CONTRACT_VALUE_EXCL_VAT) VALUES ('Abu Dhabi Plant Tissue Culture Lab', 'Presidential Court', '', 'Abu Dhabi', 'Pre-Award / Tender Stage', 4753600.0);
INSERT INTO projects_master (PROJECT_NAME, CLIENT_NAME, PROJECT_CODE, PROJECT_LOCATION_CITY, PROJECT_STATUS, CONTRACT_VALUE_EXCL_VAT) VALUES ('New Hospital at Delma Island - Abu Dhabi', 'RAFED', '', 'Abu Dhabi', 'Pre-Award / Tender Stage', 11895097.0);
INSERT INTO projects_master (PROJECT_NAME, CLIENT_NAME, PROJECT_CODE, PROJECT_LOCATION_CITY, PROJECT_STATUS, CONTRACT_VALUE_EXCL_VAT) VALUES ('Agricultural Genome Bank Design', 'Abu Dhabi Agriculture & Food Safety Authority (ADAFSA)', '', 'Abu Dhabi', 'Pre-Award / Tender Stage', 13149500.0);
INSERT INTO projects_master (PROJECT_NAME, CLIENT_NAME, PROJECT_CODE, PROJECT_LOCATION_CITY, PROJECT_STATUS, CONTRACT_VALUE_EXCL_VAT) VALUES ('The Farm house', 'ZAAD DEVELOPMENT LLC', '', 'Abu Dhabi', 'Pre-Award', 4966200.0);
INSERT INTO projects_master (PROJECT_NAME, CLIENT_NAME, PROJECT_CODE, PROJECT_LOCATION_CITY, PROJECT_STATUS, CONTRACT_VALUE_EXCL_VAT) VALUES ('The Beach House', 'ZAAD DEVELOPMENT LLC', '', 'Abu Dhabi', ' Tender Stage', 5514456.0);
INSERT INTO projects_master (PROJECT_NAME, CLIENT_NAME, PROJECT_CODE, PROJECT_LOCATION_CITY, PROJECT_STATUS, CONTRACT_VALUE_EXCL_VAT) VALUES ('Lusaili & Lahbab', 'Dubai Health', '', 'Abu Dhabi', 'Pre-Award / Tender Stage', 8002900.0);
INSERT INTO projects_master (PROJECT_NAME, CLIENT_NAME, PROJECT_CODE, PROJECT_LOCATION_CITY, PROJECT_STATUS, CONTRACT_VALUE_EXCL_VAT) VALUES ('Converting  group of villas into a specialized hospital', 'AI Hospital - Private', '', 'Abu Dhabi', 'Tender Stage', 540000.0);
INSERT INTO projects_master (PROJECT_NAME, CLIENT_NAME, PROJECT_CODE, PROJECT_LOCATION_CITY, PROJECT_STATUS, CONTRACT_VALUE_EXCL_VAT) VALUES ('80-Bed General Hospital ', 'Al Ghurair', '', 'Abu Dhabi', 'Pre-Award / Tender Stage', 4298000.0);
INSERT INTO projects_master (PROJECT_NAME, CLIENT_NAME, PROJECT_CODE, PROJECT_LOCATION_CITY, PROJECT_STATUS, CONTRACT_VALUE_EXCL_VAT) VALUES ('Al Gurm Island Villa', 'ZAAD DEVELOPMENT LLC', '', 'Abu Dhabi', 'Pre-Award / Tender Stage', 6457665.5);
INSERT INTO projects_master (PROJECT_NAME, CLIENT_NAME, PROJECT_CODE, PROJECT_LOCATION_CITY, PROJECT_STATUS, CONTRACT_VALUE_EXCL_VAT) VALUES ('SSMC - Strategic Internal Expansion', 'RAFED', '', 'Abu Dhabi', 'Pre-Award / Tender Stage', 15209806.0);
INSERT INTO projects_master (PROJECT_NAME, CLIENT_NAME, PROJECT_CODE, PROJECT_LOCATION_CITY, PROJECT_STATUS, CONTRACT_VALUE_EXCL_VAT) VALUES ('Majlis Al  Amal Ground Floor, Building No: 12, DHCC, Dubai, UAE', 'Al Jalila Foundation', '', 'Abu Dhabi', 'Pre-Award / Tender Stage', 1018970.0);
INSERT INTO projects_master (PROJECT_NAME, CLIENT_NAME, PROJECT_CODE, PROJECT_LOCATION_CITY, PROJECT_STATUS, CONTRACT_VALUE_EXCL_VAT) VALUES ('Development of Up to Five (5) Clinics', 'Al Ghurair', '', 'Abu Dhabi', 'Pre-Award / Tender Stage', 21424000.0);
INSERT INTO projects_master (PROJECT_NAME, CLIENT_NAME, PROJECT_CODE, PROJECT_LOCATION_CITY, PROJECT_STATUS, CONTRACT_VALUE_EXCL_VAT) VALUES ('Central Honeybee Pest and Disease Laboratory ', 'Abu Dhabi Agriculture & Food Safety Authority (ADAFSA)', '', 'Abu Dhabi', 'Tender Stage', 5500000.0);
INSERT INTO projects_master (PROJECT_NAME, CLIENT_NAME, PROJECT_CODE, PROJECT_LOCATION_CITY, PROJECT_STATUS, CONTRACT_VALUE_EXCL_VAT) VALUES ('Specialized Rehab Hospital Extension', 'IMKAN Properties ', '', 'Abu Dhabi', ' Tender Stage', 3646000.0);